import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import ReduxProvider from "./redux/provider";
import "./styles/globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["500"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={`${poppins.variable} antialiased`}>{children}</body>
      </ReduxProvider>
    </html>
  );
}
